In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [32]:
bur = pd.read_csv('MLProject/data/bureau.csv')
#crbal = pd.read_csv('MLProject/data/credit_card_balance.csv')
#hcr = pd.read_csv('MLProject/data/HomeCredit_columns_description.csv', encoding='ISO-8859-1')
#inst = pd.read_csv('MLProject/data/installments_payments.csv')
#POS = pd.read_csv('MLProject/data/installments_payments.csv')
prev = pd.read_csv('MLProject/data/previous_application.csv')
#samp = pd.read_csv('MLProject/data/sample_submission.csv')
#bur.sample(5)
prev.sample(5)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1605951,2241973,146026,Consumer loans,14716.575,119089.44,129569.94,0.0,119089.44,TUESDAY,17,Y,1,0.0,NaN,NaN,XAP,Approved,-116,Cash through the bank,XAP,NaN,Repeater,Mobile,POS,XNA,Country-wide,10,Connectivity,10.0,low_normal,POS mobile without interest,365243.0,-76.0,194.0,365243.0,365243.0,0.0
312488,2049099,334127,Consumer loans,3543.075,16821.00,17653.50,0.0,16821.00,SATURDAY,12,Y,1,0.0,NaN,NaN,XAP,Approved,-2724,Cash through the bank,XAP,Children,New,Mobile,POS,XNA,Country-wide,51,Connectivity,6.0,high,POS mobile with interest,365243.0,-2693.0,-2543.0,-2573.0,-2569.0,1.0
219031,1603601,145682,Cash loans,NaN,0.00,0.00,NaN,NaN,WEDNESDAY,18,Y,1,NaN,NaN,NaN,XNA,Canceled,-171,XNA,XAP,NaN,Refreshed,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
557609,1529011,362152,Consumer loans,13077.135,134955.00,134955.00,0.0,134955.00,SATURDAY,11,Y,1,0.0,NaN,NaN,XAP,Refused,-565,Cash through the bank,SCO,NaN,New,Mobile,POS,XNA,Country-wide,10,Connectivity,12.0,low_normal,POS mobile without interest,NaN,NaN,NaN,NaN,NaN,NaN
42645,1715789,276828,Cash loans,11087.955,90000.00,108207.00,NaN,90000.00,WEDNESDAY,14,Y,1,NaN,NaN,NaN,XNA,Approved,-538,Cash through the bank,XAP,NaN,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-508.0,-178.0,-208.0,-205.0,1.0

In [35]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows', None)

In [14]:
test_set = pd.read_csv('MLProject/data/application_test.csv')

In [15]:
test_set.sample(4)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
1696,112049,Cash loans,F,N,Y,0,54000.0,135000.0,14305.5,135000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,Municipal apartment,0.072508,-19810,365243,-13848.0,-2879,NaN,1,0,0,1,1,0,NaN,2.0,1,1,THURSDAY,13,0,0,0,0,0,0,XNA,0.646661,0.679341,0.832785,0.3594,0.2388,0.9786,0.7076,0.0517,0.5332,0.2759,0.3750,0.4167,0.0399,0.2931,0.3310,0.0,0.0401,0.1492,0.1089,0.9786,0.7190,0.0208,0.1611,0.1379,0.3333,0.3750,0.0175,0.1304,0.1466,0.0,0.0005,0.1489,0.1061,0.9786,0.7115,0.0217,0.16,0.1379,0.3333,0.3750,0.0178,0.1223,0.1446,0.0,0.0043,reg oper account,block of flats,0.5837,Panel,No,0.0,0.0,0.0,0.0,-2613.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
23885,273864,Cash loans,M,N,Y,0,225000.0,1096020.0,52857.0,900000.0,Unaccompanied,State servant,Secondary / secondary special,Married,With parents,0.006629,-8373,-635,-1368.0,-814,NaN,1,1,0,1,0,0,Core staff,2.0,2,2,FRIDAY,9,0,0,0,0,1,1,School,NaN,0.237418,0.384207,0.0536,NaN,0.9950,0.9320,NaN,0.0000,0.1379,0.1667,0.2083,0.0498,0.0437,0.0618,0.0,0.0346,0.0546,NaN,0.9950,0.9347,NaN,0.0000,0.1379,0.1667,0.2083,0.0509,0.0478,0.0644,0.0,0.0366,0.0541,NaN,0.9950,0.9329,NaN,0.00,0.1379,0.1667,0.2083,0.0507,0.0445,0.0629,0.0,0.0353,NaN,block of flats,0.0561,Block,No,6.0,0.0,6.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
13406,197314,Cash loans,F,Y,N,0,90000.0,817560.0,30820.5,675000.0,Unaccompanied,Pensioner,Incomplete higher,Married,House / apartment,0.008068,-20993,365243,-500.0,-4340,13.0,1,0,0,1,1,0,NaN,2.0,3,3,TUESDAY,10,0,0,0,0,0,0,XNA,0.684158,0.048553,0.231439,0.0278,0.0455,0.9871,NaN,NaN,NaN,0.1034,0.0833,NaN,NaN,NaN,0.0309,NaN,NaN,0.0284,0.0472,0.9871,NaN,NaN,NaN,0.1034,0.0833,NaN,NaN,NaN,0.0322,NaN,NaN,0.0281,0.0455,0.9871,NaN,NaN,NaN,0.1034,0.0833,NaN,NaN,NaN,0.0315,NaN,NaN,NaN,block of flats,0.0254,"Stone, brick",No,2.0,1.0,2.0,1.0,-1939.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
13400,197278,Cash loans,F,N,Y,0,225000.0,295168.5,15201.0,238500.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.035792,-22996,365243,-11649.0,-5055,NaN,1,0,0,1,0,1,NaN,1.0,2,2,THURSDAY,10,0,0,0,0,0,0,XNA,0.596464,0.614039,0.255332,0.0928,0.0000,0.9836,NaN,NaN,0.0000,0.2069,0.1667,NaN,0.1235,NaN,0.0900,NaN,0.0000,0.0945,0.0000,0.9836,NaN,NaN,0.0000,0.2069,0.1667,NaN,0.1263,NaN,0.0937,NaN,0.0000,0.0937,0.0000,0.9836,NaN,NaN,0.00,0.2069,0.1667,NaN,0.1256,NaN,0.0916,NaN,0.0000,NaN,block of flats,0.0708,Panel,No,0.0,0.0,0.0,0.0,-430.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0

In [16]:
train_set = pd.read_csv('MLProject/data/application_train.csv')

In [18]:
train_set.sample(3)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
23540,127388,1,Cash loans,F,Y,Y,0,225000.0,518562.0,25078.5,463500.0,Family,Working,Secondary / secondary special,Married,House / apartment,0.030755,-16324,-1557,-2048.0,-2698,3.0,1,1,0,1,0,0,Sales staff,2.0,2,2,SATURDAY,15,0,0,0,0,0,0,Self-employed,NaN,0.333843,0.323311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,-316.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
254026,393947,0,Cash loans,F,N,Y,0,87750.0,298512.0,16798.5,270000.0,Unaccompanied,Pensioner,Secondary / secondary special,Separated,House / apartment,0.008625,-22400,365243,-2635.0,-4150,NaN,1,0,0,1,1,0,NaN,1.0,2,2,MONDAY,11,0,0,0,0,0,0,XNA,0.889787,0.459852,0.843544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
140608,263040,0,Cash loans,M,N,Y,0,135000.0,135000.0,13833.0,135000.0,Unaccompanied,Working,Incomplete higher,Married,House / apartment,0.032561,-12011,-1246,-4303.0,-4303,NaN,1,1,0,1,1,0,Sales staff,2.0,1,1,TUESDAY,11,0,0,0,0,0,0,Trade: type 2,0.228604,0.695242,NaN,0.7093,0.4845,0.9811,0.7416,0.0,0.72,0.6207,0.3333,0.375,0.0861,0.5774,0.0,0.0039,0.0408,0.7227,0.5028,0.9811,0.7517,0.0,0.725,0.6207,0.3333,0.375,0.0881,0.6309,0.0,0.0039,0.0432,0.7161,0.4845,0.9811,0.7451,0.0,0.72,0.6207,0.3333,0.375,0.0876,0.5874,0.0,0.0039,0.0417,reg oper account,block of flats,0.6478,Panel,No,1.0,1.0,1.0,0.0,-516.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
test_set.columns = test_set.columns.str.lower().str.replace(' ', '_') # A
string_columns = list(test_set.dtypes[test_set.dtypes == 'object'].index) # B
for col in string_columns:
    test_set[col] = test_set[col].str.lower().str.replace(' ', '_') # C
test_set.shape
#test_set.info()
test_set.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Columns: 121 entries, sk_id_curr to amt_req_credit_bureau_year
dtypes: float64(65), int64(40), object(16)
memory usage: 45.0+ MB

sk_id_curr                    48744
name_contract_type                2
code_gender                       2
flag_own_car                      2
flag_own_realty                   2
                              ...
amt_req_credit_bureau_day         3
amt_req_credit_bureau_week        3
amt_req_credit_bureau_mon         7
amt_req_credit_bureau_qrt         8
amt_req_credit_bureau_year       16
Length: 121, dtype: int64

In [43]:
train_set.columns = train_set.columns.str.lower().str.replace(' ', '_') # A
string_columns = list(train_set.dtypes[train_set.dtypes == 'object'].index) # B
for col in string_columns:
    train_set[col] = train_set[col].str.lower().str.replace(' ', '_') # C
train_set.shape
#train_set.info()
train_set.nunique()

sk_id_curr                      307511
target                               2
name_contract_type                   2
code_gender                          3
flag_own_car                         2
flag_own_realty                      2
cnt_children                        15
amt_income_total                  2548
amt_credit                        5603
amt_annuity                      13672
amt_goods_price                   1002
name_type_suite                      7
name_income_type                     8
name_education_type                  5
name_family_status                   6
name_housing_type                    6
region_population_relative          81
days_birth                       17460
days_employed                    12574
days_registration                15688
days_id_publish                   6168
own_car_age                         62
flag_mobil                           2
flag_emp_phone                       2
flag_work_phone                      2
flag_cont_mobile                     2
flag_phone                           2
flag_email                           2
occupation_type                     18
cnt_fam_members                     17
region_rating_client                 3
region_rating_client_w_city          3
weekday_appr_process_start           7
hour_appr_process_start             24
reg_region_not_live_region           2
reg_region_not_work_region           2
live_region_not_work_region          2
reg_city_not_live_city               2
reg_city_not_work_city               2
live_city_not_work_city              2
organization_type                   58
ext_source_1                    114584
ext_source_2                    119831
ext_source_3                       814
apartments_avg                    2339
basementarea_avg                  3780
years_beginexpluatation_avg        285
years_build_avg                    149
commonarea_avg                    3181
elevators_avg                      257
entrances_avg                      285
floorsmax_avg                      403
floorsmin_avg                      305
landarea_avg                      3527
livingapartments_avg              1868
livingarea_avg                    5199
nonlivingapartments_avg            386
nonlivingarea_avg                 3290
apartments_mode                    760
basementarea_mode                 3841
years_beginexpluatation_mode       221
years_build_mode                   154
commonarea_mode                   3128
elevators_mode                      26
entrances_mode                      30
floorsmax_mode                      25
floorsmin_mode                      25
landarea_mode                     3563
livingapartments_mode              736
livingarea_mode                   5301
nonlivingapartments_mode           167
nonlivingarea_mode                3327
apartments_medi                   1148
basementarea_medi                 3772
years_beginexpluatation_medi       245
years_build_medi                   151
commonarea_medi                   3202
elevators_medi                      46
entrances_medi                      46
floorsmax_medi                      49
floorsmin_medi                      47
landarea_medi                     3560
livingapartments_medi             1097
livingarea_medi                   5281
nonlivingapartments_medi           214
nonlivingarea_medi                3323
fondkapremont_mode                   4
housetype_mode                       3
totalarea_mode                    5116
wallsmaterial_mode                   7
emergencystate_mode                  2
obs_30_cnt_social_circle            33
def_30_cnt_social_circle            10
obs_60_cnt_social_circle            33
def_60_cnt_social_circle             9
days_last_phone_change            3773
flag_document_2                      2
flag_document_3                      2
flag_document_4                      2
flag_document_5                      2
flag_document_6                      2
flag_document_7                      2
flag_document_8                      2
flag_document_9                      2
flag_document_10                     2
flag_document_11                     2
flag_document_12                     2
flag_document_13                     2
flag_document_14                     2
flag_document_15                     2
flag_document_16                     2
flag_document_17                     2
flag_document_18                     2
flag_document_19                     2
flag_document_20                     2
flag_document_21                     2
amt_req_credit_bureau_hour           5
amt_req_credit_bureau_day            9
amt_req_credit_bureau_week           9
amt_req_credit_bureau_mon           24
amt_req_credit_bureau_qrt           11
amt_req_credit_bureau_year          25
dtype: int64

In [44]:
test_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Columns: 121 entries, sk_id_curr to amt_req_credit_bureau_year
dtypes: float64(65), int64(40), object(16)
memory usage: 45.0+ MB

In [45]:
train_set.info(max_cols=122)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 122 columns):
 #    Column                        Non-Null Count   Dtype
---   ------                        --------------   -----
 0    sk_id_curr                    307511 non-null  int64
 1    target                        307511 non-null  int64
 2    name_contract_type            307511 non-null  object
 3    code_gender                   307511 non-null  object
 4    flag_own_car                  307511 non-null  object
 5    flag_own_realty               307511 non-null  object
 6    cnt_children                  307511 non-null  int64
 7    amt_income_total              307511 non-null  float64
 8    amt_credit                    307511 non-null  float64
 9    amt_annuity                   307499 non-null  float64
 10   amt_goods_price               307233 non-null  float64
 11   name_type_suite               306219 non-null  object
 12   name_income_type              307511 non-null  object
 13   name_education_type           307511 non-null  object
 14   name_family_status            307511 non-null  object
 15   name_housing_type             307511 non-null  object
 16   region_population_relative    307511 non-null  float64
 17   days_birth                    307511 non-null  int64
 18   days_employed                 307511 non-null  int64
 19   days_registration             307511 non-null  float64
 20   days_id_publish               307511 non-null  int64
 21   own_car_age                   104582 non-null  float64
 22   flag_mobil                    307511 non-null  int64
 23   flag_emp_phone                307511 non-null  int64
 24   flag_work_phone               307511 non-null  int64
 25   flag_cont_mobile              307511 non-null  int64
 26   flag_phone                    307511 non-null  int64
 27   flag_email                    307511 non-null  int64
 28   occupation_type               211120 non-null  object
 29   cnt_fam_members               307509 non-null  float64
 30   region_rating_client          307511 non-null  int64
 31   region_rating_client_w_city   307511 non-null  int64
 32   weekday_appr_process_start    307511 non-null  object
 33   hour_appr_process_start       307511 non-null  int64
 34   reg_region_not_live_region    307511 non-null  int64
 35   reg_region_not_work_region    307511 non-null  int64
 36   live_region_not_work_region   307511 non-null  int64
 37   reg_city_not_live_city        307511 non-null  int64
 38   reg_city_not_work_city        307511 non-null  int64
 39   live_city_not_work_city       307511 non-null  int64
 40   organization_type             307511 non-null  object
 41   ext_source_1                  134133 non-null  float64
 42   ext_source_2                  306851 non-null  float64
 43   ext_source_3                  246546 non-null  float64
 44   apartments_avg                151450 non-null  float64
 45   basementarea_avg              127568 non-null  float64
 46   years_beginexpluatation_avg   157504 non-null  float64
 47   years_build_avg               103023 non-null  float64
 48   commonarea_avg                92646 non-null   float64
 49   elevators_avg                 143620 non-null  float64
 50   entrances_avg                 152683 non-null  float64
 51   floorsmax_avg                 154491 non-null  float64
 52   floorsmin_avg                 98869 non-null   float64
 53   landarea_avg                  124921 non-null  float64
 54   livingapartments_avg          97312 non-null   float64
 55   livingarea_avg                153161 non-null  float64
 56   nonlivingapartments_avg       93997 non-null   float64
 57   nonlivingarea_avg             137829 non-null  float64
 58   apartments_mode               151450 non-null  float64
 59   basementarea_mode             127568 non-null  float64
 60   years_beginexpluatation_mode  157504 non-null  float64
 61   years_build_mode              103023 non-null  float64
 62   commonarea_mode               92646 non-null   float64
 63   elevators_mode                143620 non-null  float64
 64   entrances_mode                152683 non-null  float64
 65   floorsmax_mode                154491 non-null  float64
 66   floorsmin_mode                98869 non-null   float64
 67   landarea_mode                 124921 non-null  float64
 68   livingapartments_mode         97312 non-null   float64
 69   livingarea_mode               153161 non-null  float64
 70   nonlivingapartments_mode      93997 non-null   float64
 71   nonlivingarea_mode            137829 non-null  float64
 72   apartments_medi               151450 non-null  float64
 73   basementarea_medi             127568 non-null  float64
 74   years_beginexpluatation_medi  157504 non-null  float64
 75   years_build_medi              103023 non-null  float64
 76   commonarea_medi               92646 non-null   float64
 77   elevators_medi                143620 non-null  float64
 78   entrances_medi                152683 non-null  float64
 79   floorsmax_medi                154491 non-null  float64
 80   floorsmin_medi                98869 non-null   float64
 81   landarea_medi                 124921 non-null  float64
 82   livingapartments_medi         97312 non-null   float64
 83   livingarea_medi               153161 non-null  float64
 84   nonlivingapartments_medi      93997 non-null   float64
 85   nonlivingarea_medi            137829 non-null  float64
 86   fondkapremont_mode            97216 non-null   object
 87   housetype_mode                153214 non-null  object
 88   totalarea_mode                159080 non-null  float64
 89   wallsmaterial_mode            151170 non-null  object
 90   emergencystate_mode           161756 non-null  object
 91   obs_30_cnt_social_circle      306490 non-null  float64
 92   def_30_cnt_social_circle      306490 non-null  float64
 93   obs_60_cnt_social_circle      306490 non-null  float64
 94   def_60_cnt_social_circle      306490 non-null  float64
 95   days_last_phone_change        307510 non-null  float64
 96   flag_document_2               307511 non-null  int64
 97   flag_document_3               307511 non-null  int64
 98   flag_document_4               307511 non-null  int64
 99   flag_document_5               307511 non-null  int64
 100  flag_document_6               307511 non-null  int64
 101  flag_document_7               307511 non-null  int64
 102  flag_document_8               307511 non-null  int64
 103  flag_document_9               307511 non-null  int64
 104  flag_document_10              307511 non-null  int64
 105  flag_document_11              307511 non-null  int64
 106  flag_document_12              307511 non-null  int64
 107  flag_document_13              307511 non-null  int64
 108  flag_document_14              307511 non-null  int64
 109  flag_document_15              307511 non-null  int64
 110  flag_document_16              307511 non-null  int64
 111  flag_document_17              307511 non-null  int64
 112  flag_document_18              307511 non-null  int64
 113  flag_document_19              307511 non-null  int64
 114  flag_document_20              307511 non-null  int64
 115  flag_document_21              307511 non-null  int64
 116  amt_req_credit_bureau_hour    265992 non-null  float64
 117  amt_req_credit_bureau_day     265992 non-null  float64
 118  amt_req_credit_bureau_week    265992 non-null  float64
 119  amt_req_credit_bureau_mon     265992 non-null  float64
 120  amt_req_credit_bureau_qrt     265992 non-null  float64
 121  amt_req_credit_bureau_year    265992 non-null  float64
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

In [38]:
test_set.dtypes

sk_id_curr                        int64
name_contract_type               object
code_gender                      object
flag_own_car                     object
flag_own_realty                  object
cnt_children                      int64
amt_income_total                float64
amt_credit                      float64
amt_annuity                     float64
amt_goods_price                 float64
name_type_suite                  object
name_income_type                 object
name_education_type              object
name_family_status               object
name_housing_type                object
region_population_relative      float64
days_birth                        int64
days_employed                     int64
days_registration               float64
days_id_publish                   int64
own_car_age                     float64
flag_mobil                        int64
flag_emp_phone                    int64
flag_work_phone                   int64
flag_cont_mobile                  int64
flag_phone                        int64
flag_email                        int64
occupation_type                  object
cnt_fam_members                 float64
region_rating_client              int64
region_rating_client_w_city       int64
weekday_appr_process_start       object
hour_appr_process_start           int64
reg_region_not_live_region        int64
reg_region_not_work_region        int64
live_region_not_work_region       int64
reg_city_not_live_city            int64
reg_city_not_work_city            int64
live_city_not_work_city           int64
organization_type                object
ext_source_1                    float64
ext_source_2                    float64
ext_source_3                    float64
apartments_avg                  float64
basementarea_avg                float64
years_beginexpluatation_avg     float64
years_build_avg                 float64
commonarea_avg                  float64
elevators_avg                   float64
entrances_avg                   float64
floorsmax_avg                   float64
floorsmin_avg                   float64
landarea_avg                    float64
livingapartments_avg            float64
livingarea_avg                  float64
nonlivingapartments_avg         float64
nonlivingarea_avg               float64
apartments_mode                 float64
basementarea_mode               float64
years_beginexpluatation_mode    float64
years_build_mode                float64
commonarea_mode                 float64
elevators_mode                  float64
entrances_mode                  float64
floorsmax_mode                  float64
floorsmin_mode                  float64
landarea_mode                   float64
livingapartments_mode           float64
livingarea_mode                 float64
nonlivingapartments_mode        float64
nonlivingarea_mode              float64
apartments_medi                 float64
basementarea_medi               float64
years_beginexpluatation_medi    float64
years_build_medi                float64
commonarea_medi                 float64
elevators_medi                  float64
entrances_medi                  float64
floorsmax_medi                  float64
floorsmin_medi                  float64
landarea_medi                   float64
livingapartments_medi           float64
livingarea_medi                 float64
nonlivingapartments_medi        float64
nonlivingarea_medi              float64
fondkapremont_mode               object
housetype_mode                   object
totalarea_mode                  float64
wallsmaterial_mode               object
emergencystate_mode              object
obs_30_cnt_social_circle        float64
def_30_cnt_social_circle        float64
obs_60_cnt_social_circle        float64
def_60_cnt_social_circle        float64
days_last_phone_change          float64
flag_document_2                   int64
flag_document_3                   int64
flag_document_4                   int64
flag_document_5                   int64
flag_document_6                   int64
flag_document_7                   int64
flag_document_8                   int64
flag_document_9                   int64
flag_document_10                  int64
flag_document_11                  int64
flag_document_12                  int64
flag_document_13                  int64
flag_document_14                  int64
flag_document_15                  int64
flag_document_16                  int64
flag_document_17                  int64
flag_document_18                  int64
flag_document_19                  int64
flag_document_20                  int64
flag_document_21                  int64
amt_req_credit_bureau_hour      float64
amt_req_credit_bureau_day       float64
amt_req_credit_bureau_week      float64
amt_req_credit_bureau_mon       float64
amt_req_credit_bureau_qrt       float64
amt_req_credit_bureau_year      float64
dtype: object

In [30]:
import seaborn as sns 
import matplotlib.pyplot as plt

#corr = train_set.corr()
#sns.heatmap(corr)
# plt.figure(figsize=(3,3), dpi=100)
#plt.gcf().set_size_inches(20, 10)#
#plt.show()

In [41]:
#train_set.isnull().sum()

In [42]:
#test_set.isnull().sum()

In [50]:
train_set.dtypes.value_counts()

float64    65
int64      41
object     16
dtype: int64

In [51]:
train_set.dtypes

sk_id_curr                        int64
target                            int64
name_contract_type               object
code_gender                      object
flag_own_car                     object
flag_own_realty                  object
cnt_children                      int64
amt_income_total                float64
amt_credit                      float64
amt_annuity                     float64
amt_goods_price                 float64
name_type_suite                  object
name_income_type                 object
name_education_type              object
name_family_status               object
name_housing_type                object
region_population_relative      float64
days_birth                        int64
days_employed                     int64
days_registration               float64
days_id_publish                   int64
own_car_age                     float64
flag_mobil                        int64
flag_emp_phone                    int64
flag_work_phone                   int64
flag_cont_mobile                  int64
flag_phone                        int64
flag_email                        int64
occupation_type                  object
cnt_fam_members                 float64
region_rating_client              int64
region_rating_client_w_city       int64
weekday_appr_process_start       object
hour_appr_process_start           int64
reg_region_not_live_region        int64
reg_region_not_work_region        int64
live_region_not_work_region       int64
reg_city_not_live_city            int64
reg_city_not_work_city            int64
live_city_not_work_city           int64
organization_type                object
ext_source_1                    float64
ext_source_2                    float64
ext_source_3                    float64
apartments_avg                  float64
basementarea_avg                float64
years_beginexpluatation_avg     float64
years_build_avg                 float64
commonarea_avg                  float64
elevators_avg                   float64
entrances_avg                   float64
floorsmax_avg                   float64
floorsmin_avg                   float64
landarea_avg                    float64
livingapartments_avg            float64
livingarea_avg                  float64
nonlivingapartments_avg         float64
nonlivingarea_avg               float64
apartments_mode                 float64
basementarea_mode               float64
years_beginexpluatation_mode    float64
years_build_mode                float64
commonarea_mode                 float64
elevators_mode                  float64
entrances_mode                  float64
floorsmax_mode                  float64
floorsmin_mode                  float64
landarea_mode                   float64
livingapartments_mode           float64
livingarea_mode                 float64
nonlivingapartments_mode        float64
nonlivingarea_mode              float64
apartments_medi                 float64
basementarea_medi               float64
years_beginexpluatation_medi    float64
years_build_medi                float64
commonarea_medi                 float64
elevators_medi                  float64
entrances_medi                  float64
floorsmax_medi                  float64
floorsmin_medi                  float64
landarea_medi                   float64
livingapartments_medi           float64
livingarea_medi                 float64
nonlivingapartments_medi        float64
nonlivingarea_medi              float64
fondkapremont_mode               object
housetype_mode                   object
totalarea_mode                  float64
wallsmaterial_mode               object
emergencystate_mode              object
obs_30_cnt_social_circle        float64
def_30_cnt_social_circle        float64
obs_60_cnt_social_circle        float64
def_60_cnt_social_circle        float64
days_last_phone_change          float64
flag_document_2                   int64
flag_document_3                   int64
flag_document_4                   int64
flag_document_5                   int64
flag_document_6                   int64
flag_document_7                   int64
flag_document_8                   int64
flag_document_9                   int64
flag_document_10                  int64
flag_document_11                  int64
flag_document_12                  int64
flag_document_13                  int64
flag_document_14                  int64
flag_document_15                  int64
flag_document_16                  int64
flag_document_17                  int64
flag_document_18                  int64
flag_document_19                  int64
flag_document_20                  int64
flag_document_21                  int64
amt_req_credit_bureau_hour      float64
amt_req_credit_bureau_day       float64
amt_req_credit_bureau_week      float64
amt_req_credit_bureau_mon       float64
amt_req_credit_bureau_qrt       float64
amt_req_credit_bureau_year      float64
dtype: object

In [52]:
#Categorical data unique values for each categorical item 
train_set.select_dtypes(include=[object]).apply(pd.Series.nunique, axis = 0)

name_contract_type             2
code_gender                    3
flag_own_car                   2
flag_own_realty                2
name_type_suite                7
name_income_type               8
name_education_type            5
name_family_status             6
name_housing_type              6
occupation_type               18
weekday_appr_process_start     7
organization_type             58
fondkapremont_mode             4
housetype_mode                 3
wallsmaterial_mode             7
emergencystate_mode            2
dtype: int64

In [59]:
#Target Value distribution ( 0: Repays loan on time , 1: has difficulty in repaying loan on time)
train_set.target.value_counts()

0    282686
1     24825
Name: target, dtype: int64

In [63]:
#Finding columns with most missing or null values 
train_set.isnull().sum().sort_values(ascending=False).head(20)

commonarea_medi             214865
commonarea_avg              214865
commonarea_mode             214865
nonlivingapartments_mode    213514
nonlivingapartments_avg     213514
nonlivingapartments_medi    213514
fondkapremont_mode          210295
livingapartments_mode       210199
livingapartments_avg        210199
livingapartments_medi       210199
floorsmin_avg               208642
floorsmin_mode              208642
floorsmin_medi              208642
years_build_medi            204488
years_build_mode            204488
years_build_avg             204488
own_car_age                 202929
landarea_medi               182590
landarea_mode               182590
landarea_avg                182590
dtype: int64

In [64]:
#train_set.describe()

,sk_id_curr,target,cnt_children,amt_income_total,amt_credit,amt_annuity,amt_goods_price,region_population_relative,days_birth,days_employed,days_registration,days_id_publish,own_car_age,flag_mobil,flag_emp_phone,flag_work_phone,flag_cont_mobile,flag_phone,flag_email,cnt_fam_members,region_rating_client,region_rating_client_w_city,hour_appr_process_start,reg_region_not_live_region,reg_region_not_work_region,live_region_not_work_region,reg_city_not_live_city,reg_city_not_work_city,live_city_not_work_city,ext_source_1,ext_source_2,ext_source_3,apartments_avg,basementarea_avg,years_beginexpluatation_avg,years_build_avg,commonarea_avg,elevators_avg,entrances_avg,floorsmax_avg,floorsmin_avg,landarea_avg,livingapartments_avg,livingarea_avg,nonlivingapartments_avg,nonlivingarea_avg,apartments_mode,basementarea_mode,years_beginexpluatation_mode,years_build_mode,commonarea_mode,elevators_mode,entrances_mode,floorsmax_mode,floorsmin_mode,landarea_mode,livingapartments_mode,livingarea_mode,nonlivingapartments_mode,nonlivingarea_mode,apartments_medi,basementarea_medi,years_beginexpluatation_medi,years_build_medi,commonarea_medi,elevators_medi,entrances_medi,floorsmax_medi,floorsmin_medi,landarea_medi,livingapartments_medi,livingarea_medi,nonlivingapartments_medi,nonlivingarea_medi,totalarea_mode,obs_30_cnt_social_circle,def_30_cnt_social_circle,obs_60_cnt_social_circle,def_60_cnt_social_circle,days_last_phone_change,flag_document_2,flag_document_3,flag_document_4,flag_document_5,flag_document_6,flag_document_7,flag_document_8,flag_document_9,flag_document_10,flag_document_11,flag_document_12,flag_document_13,flag_document_14,flag_document_15,flag_document_16,flag_document_17,flag_document_18,flag_document_19,flag_document_20,flag_document_21,amt_req_credit_bureau_hour,amt_req_credit_bureau_day,amt_req_credit_bureau_week,amt_req_credit_bureau_mon,amt_req_credit_bureau_qrt,amt_req_credit_bureau_year
count,307511.000000,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,3.072330e+05,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,104582.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307509.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,134133.000000,3.068510e+05,246546.000000,151450.00000,127568.000000,157504.000000,103023.000000,92646.000000,143620.000000,152683.000000,154491.000000,98869.000000,124921.000000,97312.000000,153161.000000,93997.000000,137829.000000,151450.000000,127568.000000,157504.000000,103023.000000,92646.000000,143620.000000,152683.000000,154491.000000,98869.000000,124921.000000,97312.000000,153161.000000,93997.000000,137829.000000,151450.000000,127568.000000,157504.000000,103023.000000,92646.000000,143620.000000,152683.000000,154491.000000,98869.000000,124921.000000,97312.000000,153161.000000,93997.000000,137829.000000,159080.000000,306490.000000,306490.000000,306490.000000,306490.000000,307510.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.00000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,307511.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000
mean,278180.518577,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,5.383962e+05,0.020868,-16036.995067,63815.045904,-4986.120328,-2994.202373,12.061091,0.999997,0.819889,0.199368,0.998133,0.281066,0.056720,2.152665,2.052463,2.031521,12.063419,0.015144,0.050769,0.040659,0.078173,0.230454,0.179555,0.502130,5.143927e-01,0.510853,0.11744,0.088442,0.977735,0.752471,0.044621,0.078942,0.149725,0.226282,0.231894,0.066333,0.100775,0.107399,0.008809,0.028358,0.114231,0.087543,0.977065,0.759637,0.042553,0.074490,0.145193,0.222315,0.228058,0.064958,0.105645,0.105975,0.008076,0.027022,0.117850,0.087955,0.977752,0.755746,0.044595,0.078078,0.149213,0.225897,0.231625,0.067169,0.101954,0.108607,0.008651,0.028236,0.102547,1.422245,0.143421,1.405292,0.100049,-962.858788,0.000042,0.710023,0.000081,0.015115,0.088055,0.000192,0.081376,0.003896,0.000023,0.003912,0.000007,0.003525,0.002936,0.00121,0.009928,0.000267,0.008130,0.000595,0.000507,0.000335,0.006402,0.007000,0.034362,0.267395,0.265474,1.899974
std,102790.175348,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,3.694465e+05,0.013831,4363.988632,141275.766519,3522.886321,1509.450419,11.944812,0.001803,0.384280,0.399526,0.043164,0.449521,0.231307,0.910682,0.509034,0.502737,3.265832,0.122126,0.219526,0.197499,0.268444,0.421124,0.383817,0.211062,1.910602e-01,0.194844,0.10824,0.082438,0.059223,0.113280,0.076036,0.134576,0.100049,0.144641,0.161380,0.081184,0.092576,0.110565,0.047732,0.069523,0.107936,0.084307,0.064575,0.110111,0.074445,0.132256,0.100977,0.143709,0.161160,0.081750,0.097880,0.111845,0.046276,0.070254,0.109076,0.082179,0.059897,0.112066,0.076144,0.134467,0.100368,0.145067,0.161934,0.082167,0.093642,0.112260,0.047415,0.070166,0.107462,2.400989,0.446698,2.379803,0.362291,826.808487,0.006502,0.453752,0.009016,0.122010,0.283376,0.013850,0.273412,0.062295,0.004771,0.062424,0.002550,0.059268,0.054110,0.03476,0.099144,0.016327,0.089798,0.024387,0.022518,0.018299,0.083849,0.110757,0.204685,0.916002,0.794056,1.869295
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,-24672.000000,-7197.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.014568,8.173617e-08,0.000527,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4292.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,189145.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,0.010006,-19682.000000,-2760.000000,-7479.500000,-4299.000000,5.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.334007,3.924574e-01,0.370650,0.05770,0.044200,0.976700,0.687200,0.007800,0.000000,0.069000,0.166700,0.083300,0.018700,0.050400,0.045300,0.000000,0.000000,0.052500,0.040700,0.976700,0.699400,0.007200,0.000000,0.069000,0.166700,0.083300,0.016600,0.054200,0.042700,0.000000,0.000000,0.058300,0.043700,0.976700,0.691400,0.007900,0.000000,0.069000,0.166700,0.083300,0.018700,0.051300,0.045700,0.000000,0.000000,0.041200,0.000000,0.000000,0.000000,0.000000,-1570.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,278202.000000,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,0.018850,-15750.000000,-1213.000000,-4504.000000,-3254.000000,9.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.505998,5.659614e-01,0.535276,0.08760,0.076300,0.981600,0.755200,0.021100,0.000000,0.137900,0.166700,0.208300,0.048100,0.075600,0.074500,0.000000,0.003600,0.084000,0.074600,0.981600,0.764800,0.019000,0.000000,0.137900,0.166700,0.208300,0.045800,0.077100,0.073100,0.000000,0.001100,0.086400,0.075800,0.981600,0.758500,0.020800,0.000000,0.137900,0.166700,0.208300,0.048700,0.076100,0.074900,0.000000,0.003100,0.068800,0.000000,0.000000,0.000000,0.000000,-757.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,367142.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12413.000000,-289.000000,-2010.000000,-1720.000000,15.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,3.000000,2.000000,2.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.675053,6.636171e-01,0.669057,0.14850,0.112200,0.986600,0.823200,0.051500,0.120000,0.206900,0.333300,0.375000,0.085600,0.121000,0.129900,0.003900,0.027700,0.143900,0.112400,0.986600,0.823600,0.049000,0.120800,0.206900,0.333300,0.375000,0.084100,0.131300,0.125200,0.003900,0.023100,0.148900,0.111600,0.986600,0.825600,0.051300,0.120000,0.206900,0.333300,0.375000,0.086800,0.123100,0.130300,0.003900,0.026600,0.127600,2.000000,0.000000,2.000000,0.000000,-274.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,456255.000000,1.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,365243.000000,0.000000,0.000000,91.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,20.000000,3.000000,3.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.962693,8.549997e-01,0.896010,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,348.000000,34.000000,344.000000,24.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,9.000000,8.000000,27.000000,261.000000,25.000000

In [ ]:
#train_set.fillna(-999)

In [ ]:
train_set.sample(5)