In [5]:
import pandas as pd

In [32]:
bur = pd.read_csv('MLProject/data/bureau.csv')
#crbal = pd.read_csv('MLProject/data/credit_card_balance.csv')
#hcr = pd.read_csv('MLProject/data/HomeCredit_columns_description.csv', encoding='ISO-8859-1')
#inst = pd.read_csv('MLProject/data/installments_payments.csv')
#POS = pd.read_csv('MLProject/data/installments_payments.csv')
prev = pd.read_csv('MLProject/data/previous_application.csv')
#samp = pd.read_csv('MLProject/data/sample_submission.csv')
#bur.sample(5)
prev.sample(5)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
1605951,2241973,146026,Consumer loans,14716.575,119089.44,129569.94,0.0,119089.44,TUESDAY,17,Y,1,0.0,NaN,NaN,XAP,Approved,-116,Cash through the bank,XAP,NaN,Repeater,Mobile,POS,XNA,Country-wide,10,Connectivity,10.0,low_normal,POS mobile without interest,365243.0,-76.0,194.0,365243.0,365243.0,0.0
312488,2049099,334127,Consumer loans,3543.075,16821.00,17653.50,0.0,16821.00,SATURDAY,12,Y,1,0.0,NaN,NaN,XAP,Approved,-2724,Cash through the bank,XAP,Children,New,Mobile,POS,XNA,Country-wide,51,Connectivity,6.0,high,POS mobile with interest,365243.0,-2693.0,-2543.0,-2573.0,-2569.0,1.0
219031,1603601,145682,Cash loans,NaN,0.00,0.00,NaN,NaN,WEDNESDAY,18,Y,1,NaN,NaN,NaN,XNA,Canceled,-171,XNA,XAP,NaN,Refreshed,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
557609,1529011,362152,Consumer loans,13077.135,134955.00,134955.00,0.0,134955.00,SATURDAY,11,Y,1,0.0,NaN,NaN,XAP,Refused,-565,Cash through the bank,SCO,NaN,New,Mobile,POS,XNA,Country-wide,10,Connectivity,12.0,low_normal,POS mobile without interest,NaN,NaN,NaN,NaN,NaN,NaN
42645,1715789,276828,Cash loans,11087.955,90000.00,108207.00,NaN,90000.00,WEDNESDAY,14,Y,1,NaN,NaN,NaN,XNA,Approved,-538,Cash through the bank,XAP,NaN,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-508.0,-178.0,-208.0,-205.0,1.0

In [35]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows', None)

In [14]:
test_set = pd.read_csv('MLProject/data/application_test.csv')

In [15]:
test_set.sample(4)

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
1696,112049,Cash loans,F,N,Y,0,54000.0,135000.0,14305.5,135000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,Municipal apartment,0.072508,-19810,365243,-13848.0,-2879,NaN,1,0,0,1,1,0,NaN,2.0,1,1,THURSDAY,13,0,0,0,0,0,0,XNA,0.646661,0.679341,0.832785,0.3594,0.2388,0.9786,0.7076,0.0517,0.5332,0.2759,0.3750,0.4167,0.0399,0.2931,0.3310,0.0,0.0401,0.1492,0.1089,0.9786,0.7190,0.0208,0.1611,0.1379,0.3333,0.3750,0.0175,0.1304,0.1466,0.0,0.0005,0.1489,0.1061,0.9786,0.7115,0.0217,0.16,0.1379,0.3333,0.3750,0.0178,0.1223,0.1446,0.0,0.0043,reg oper account,block of flats,0.5837,Panel,No,0.0,0.0,0.0,0.0,-2613.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
23885,273864,Cash loans,M,N,Y,0,225000.0,1096020.0,52857.0,900000.0,Unaccompanied,State servant,Secondary / secondary special,Married,With parents,0.006629,-8373,-635,-1368.0,-814,NaN,1,1,0,1,0,0,Core staff,2.0,2,2,FRIDAY,9,0,0,0,0,1,1,School,NaN,0.237418,0.384207,0.0536,NaN,0.9950,0.9320,NaN,0.0000,0.1379,0.1667,0.2083,0.0498,0.0437,0.0618,0.0,0.0346,0.0546,NaN,0.9950,0.9347,NaN,0.0000,0.1379,0.1667,0.2083,0.0509,0.0478,0.0644,0.0,0.0366,0.0541,NaN,0.9950,0.9329,NaN,0.00,0.1379,0.1667,0.2083,0.0507,0.0445,0.0629,0.0,0.0353,NaN,block of flats,0.0561,Block,No,6.0,0.0,6.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
13406,197314,Cash loans,F,Y,N,0,90000.0,817560.0,30820.5,675000.0,Unaccompanied,Pensioner,Incomplete higher,Married,House / apartment,0.008068,-20993,365243,-500.0,-4340,13.0,1,0,0,1,1,0,NaN,2.0,3,3,TUESDAY,10,0,0,0,0,0,0,XNA,0.684158,0.048553,0.231439,0.0278,0.0455,0.9871,NaN,NaN,NaN,0.1034,0.0833,NaN,NaN,NaN,0.0309,NaN,NaN,0.0284,0.0472,0.9871,NaN,NaN,NaN,0.1034,0.0833,NaN,NaN,NaN,0.0322,NaN,NaN,0.0281,0.0455,0.9871,NaN,NaN,NaN,0.1034,0.0833,NaN,NaN,NaN,0.0315,NaN,NaN,NaN,block of flats,0.0254,"Stone, brick",No,2.0,1.0,2.0,1.0,-1939.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
13400,197278,Cash loans,F,N,Y,0,225000.0,295168.5,15201.0,238500.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.035792,-22996,365243,-11649.0,-5055,NaN,1,0,0,1,0,1,NaN,1.0,2,2,THURSDAY,10,0,0,0,0,0,0,XNA,0.596464,0.614039,0.255332,0.0928,0.0000,0.9836,NaN,NaN,0.0000,0.2069,0.1667,NaN,0.1235,NaN,0.0900,NaN,0.0000,0.0945,0.0000,0.9836,NaN,NaN,0.0000,0.2069,0.1667,NaN,0.1263,NaN,0.0937,NaN,0.0000,0.0937,0.0000,0.9836,NaN,NaN,0.00,0.2069,0.1667,NaN,0.1256,NaN,0.0916,NaN,0.0000,NaN,block of flats,0.0708,Panel,No,0.0,0.0,0.0,0.0,-430.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0

In [16]:
train_set = pd.read_csv('MLProject/data/application_train.csv')

In [18]:
train_set.sample(3)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
23540,127388,1,Cash loans,F,Y,Y,0,225000.0,518562.0,25078.5,463500.0,Family,Working,Secondary / secondary special,Married,House / apartment,0.030755,-16324,-1557,-2048.0,-2698,3.0,1,1,0,1,0,0,Sales staff,2.0,2,2,SATURDAY,15,0,0,0,0,0,0,Self-employed,NaN,0.333843,0.323311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,-316.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
254026,393947,0,Cash loans,F,N,Y,0,87750.0,298512.0,16798.5,270000.0,Unaccompanied,Pensioner,Secondary / secondary special,Separated,House / apartment,0.008625,-22400,365243,-2635.0,-4150,NaN,1,0,0,1,1,0,NaN,1.0,2,2,MONDAY,11,0,0,0,0,0,0,XNA,0.889787,0.459852,0.843544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
140608,263040,0,Cash loans,M,N,Y,0,135000.0,135000.0,13833.0,135000.0,Unaccompanied,Working,Incomplete higher,Married,House / apartment,0.032561,-12011,-1246,-4303.0,-4303,NaN,1,1,0,1,1,0,Sales staff,2.0,1,1,TUESDAY,11,0,0,0,0,0,0,Trade: type 2,0.228604,0.695242,NaN,0.7093,0.4845,0.9811,0.7416,0.0,0.72,0.6207,0.3333,0.375,0.0861,0.5774,0.0,0.0039,0.0408,0.7227,0.5028,0.9811,0.7517,0.0,0.725,0.6207,0.3333,0.375,0.0881,0.6309,0.0,0.0039,0.0432,0.7161,0.4845,0.9811,0.7451,0.0,0.72,0.6207,0.3333,0.375,0.0876,0.5874,0.0,0.0039,0.0417,reg oper account,block of flats,0.6478,Panel,No,1.0,1.0,1.0,0.0,-516.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
test_set.columns = test_set.columns.str.lower().str.replace(' ', '_') # A
string_columns = list(test_set.dtypes[test_set.dtypes == 'object'].index) # B
for col in string_columns:
    test_set[col] = test_set[col].str.lower().str.replace(' ', '_') # C
test_set.shape
test_set.info()
test_set.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Columns: 121 entries, sk_id_curr to amt_req_credit_bureau_year
dtypes: float64(65), int64(40), object(16)
memory usage: 45.0+ MB

sk_id_curr                    48744
name_contract_type                2
code_gender                       2
flag_own_car                      2
flag_own_realty                   2
                              ...
amt_req_credit_bureau_day         3
amt_req_credit_bureau_week        3
amt_req_credit_bureau_mon         7
amt_req_credit_bureau_qrt         8
amt_req_credit_bureau_year       16
Length: 121, dtype: int64

In [37]:
train_set.columns = train_set.columns.str.lower().str.replace(' ', '_') # A
string_columns = list(train_set.dtypes[train_set.dtypes == 'object'].index) # B
for col in string_columns:
    train_set[col] = train_set[col].str.lower().str.replace(' ', '_') # C
train_set.shape
train_set.info()
train_set.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, sk_id_curr to amt_req_credit_bureau_year
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

sk_id_curr                      307511
target                               2
name_contract_type                   2
code_gender                          3
flag_own_car                         2
flag_own_realty                      2
cnt_children                        15
amt_income_total                  2548
amt_credit                        5603
amt_annuity                      13672
amt_goods_price                   1002
name_type_suite                      7
name_income_type                     8
name_education_type                  5
name_family_status                   6
name_housing_type                    6
region_population_relative          81
days_birth                       17460
days_employed                    12574
days_registration                15688
days_id_publish                   6168
own_car_age                         62
flag_mobil                           2
flag_emp_phone                       2
flag_work_phone                      2
flag_cont_mobile                     2
flag_phone                           2
flag_email                           2
occupation_type                     18
cnt_fam_members                     17
region_rating_client                 3
region_rating_client_w_city          3
weekday_appr_process_start           7
hour_appr_process_start             24
reg_region_not_live_region           2
reg_region_not_work_region           2
live_region_not_work_region          2
reg_city_not_live_city               2
reg_city_not_work_city               2
live_city_not_work_city              2
organization_type                   58
ext_source_1                    114584
ext_source_2                    119831
ext_source_3                       814
apartments_avg                    2339
basementarea_avg                  3780
years_beginexpluatation_avg        285
years_build_avg                    149
commonarea_avg                    3181
elevators_avg                      257
entrances_avg                      285
floorsmax_avg                      403
floorsmin_avg                      305
landarea_avg                      3527
livingapartments_avg              1868
livingarea_avg                    5199
nonlivingapartments_avg            386
nonlivingarea_avg                 3290
apartments_mode                    760
basementarea_mode                 3841
years_beginexpluatation_mode       221
years_build_mode                   154
commonarea_mode                   3128
elevators_mode                      26
entrances_mode                      30
floorsmax_mode                      25
floorsmin_mode                      25
landarea_mode                     3563
livingapartments_mode              736
livingarea_mode                   5301
nonlivingapartments_mode           167
nonlivingarea_mode                3327
apartments_medi                   1148
basementarea_medi                 3772
years_beginexpluatation_medi       245
years_build_medi                   151
commonarea_medi                   3202
elevators_medi                      46
entrances_medi                      46
floorsmax_medi                      49
floorsmin_medi                      47
landarea_medi                     3560
livingapartments_medi             1097
livingarea_medi                   5281
nonlivingapartments_medi           214
nonlivingarea_medi                3323
fondkapremont_mode                   4
housetype_mode                       3
totalarea_mode                    5116
wallsmaterial_mode                   7
emergencystate_mode                  2
obs_30_cnt_social_circle            33
def_30_cnt_social_circle            10
obs_60_cnt_social_circle            33
def_60_cnt_social_circle             9
days_last_phone_change            3773
flag_document_2                      2
flag_document_3                      2
flag_document_4                      2
flag_document_5                      2
flag_document_6                      2
flag_document_7                      2
flag_document_8                      2
flag_document_9                      2
flag_document_10                     2
flag_document_11                     2
flag_document_12                     2
flag_document_13                     2
flag_document_14                     2
flag_document_15                     2
flag_document_16                     2
flag_document_17                     2
flag_document_18                     2
flag_document_19                     2
flag_document_20                     2
flag_document_21                     2
amt_req_credit_bureau_hour           5
amt_req_credit_bureau_day            9
amt_req_credit_bureau_week           9
amt_req_credit_bureau_mon           24
amt_req_credit_bureau_qrt           11
amt_req_credit_bureau_year          25
dtype: int64

In [25]:
test_set.duplicated().sum()

0

In [26]:
train_set.duplicated().sum()

0

In [38]:
test_set.dtypes

sk_id_curr                        int64
name_contract_type               object
code_gender                      object
flag_own_car                     object
flag_own_realty                  object
cnt_children                      int64
amt_income_total                float64
amt_credit                      float64
amt_annuity                     float64
amt_goods_price                 float64
name_type_suite                  object
name_income_type                 object
name_education_type              object
name_family_status               object
name_housing_type                object
region_population_relative      float64
days_birth                        int64
days_employed                     int64
days_registration               float64
days_id_publish                   int64
own_car_age                     float64
flag_mobil                        int64
flag_emp_phone                    int64
flag_work_phone                   int64
flag_cont_mobile                  int64
flag_phone                        int64
flag_email                        int64
occupation_type                  object
cnt_fam_members                 float64
region_rating_client              int64
region_rating_client_w_city       int64
weekday_appr_process_start       object
hour_appr_process_start           int64
reg_region_not_live_region        int64
reg_region_not_work_region        int64
live_region_not_work_region       int64
reg_city_not_live_city            int64
reg_city_not_work_city            int64
live_city_not_work_city           int64
organization_type                object
ext_source_1                    float64
ext_source_2                    float64
ext_source_3                    float64
apartments_avg                  float64
basementarea_avg                float64
years_beginexpluatation_avg     float64
years_build_avg                 float64
commonarea_avg                  float64
elevators_avg                   float64
entrances_avg                   float64
floorsmax_avg                   float64
floorsmin_avg                   float64
landarea_avg                    float64
livingapartments_avg            float64
livingarea_avg                  float64
nonlivingapartments_avg         float64
nonlivingarea_avg               float64
apartments_mode                 float64
basementarea_mode               float64
years_beginexpluatation_mode    float64
years_build_mode                float64
commonarea_mode                 float64
elevators_mode                  float64
entrances_mode                  float64
floorsmax_mode                  float64
floorsmin_mode                  float64
landarea_mode                   float64
livingapartments_mode           float64
livingarea_mode                 float64
nonlivingapartments_mode        float64
nonlivingarea_mode              float64
apartments_medi                 float64
basementarea_medi               float64
years_beginexpluatation_medi    float64
years_build_medi                float64
commonarea_medi                 float64
elevators_medi                  float64
entrances_medi                  float64
floorsmax_medi                  float64
floorsmin_medi                  float64
landarea_medi                   float64
livingapartments_medi           float64
livingarea_medi                 float64
nonlivingapartments_medi        float64
nonlivingarea_medi              float64
fondkapremont_mode               object
housetype_mode                   object
totalarea_mode                  float64
wallsmaterial_mode               object
emergencystate_mode              object
obs_30_cnt_social_circle        float64
def_30_cnt_social_circle        float64
obs_60_cnt_social_circle        float64
def_60_cnt_social_circle        float64
days_last_phone_change          float64
flag_document_2                   int64
flag_document_3                   int64
flag_document_4                   int64
flag_document_5                   int64
flag_document_6                   int64
flag_document_7                   int64
flag_document_8                   int64
flag_document_9                   int64
flag_document_10                  int64
flag_document_11                  int64
flag_document_12                  int64
flag_document_13                  int64
flag_document_14                  int64
flag_document_15                  int64
flag_document_16                  int64
flag_document_17                  int64
flag_document_18                  int64
flag_document_19                  int64
flag_document_20                  int64
flag_document_21                  int64
amt_req_credit_bureau_hour      float64
amt_req_credit_bureau_day       float64
amt_req_credit_bureau_week      float64
amt_req_credit_bureau_mon       float64
amt_req_credit_bureau_qrt       float64
amt_req_credit_bureau_year      float64
dtype: object

In [30]:
import seaborn as sns 
import matplotlib.pyplot as plt

#corr = train_set.corr()
#sns.heatmap(corr)
# plt.figure(figsize=(3,3), dpi=100)
#plt.gcf().set_size_inches(20, 10)#
#plt.show()